object Dependencies {
    const val ActivityCompose = "androidx.activity:activity-compose:${Versions.ActivityCompose}"
    const val ComposeMaterial3 = "androidx.compose.material3:material3:${Versions.ComposeMaterial3}"
    const val ComposeMaterial = "androidx.compose.material:material:${Versions.ComposeMaterial}"
    const val ComposeUi = "androidx.compose.ui:ui"
    const val ComposeUiGraphics = "androidx.compose.ui:ui-graphics"
    const val ComposeUiToolingPreview = "androidx.compose.ui:ui-tooling-preview"
    const val ComposeUiTooling = "androidx.compose.ui:ui-tooling"
    const val ComposeBom = "androidx.compose:compose-bom:${Versions.ComposeBom}"
    const val ComposeRuntimeLivedata =
        "androidx.compose.runtime:runtime-livedata:${Versions.ComposeRuntimeLivedata}"
    const val LifecycleViewModelCompose =
        "androidx.lifecycle:lifecycle-viewmodel-compose:${Versions.LifecycleViewModelCompose}"
    const val LifecycleRuntimeCompose =
        "androidx.lifecycle:lifecycle-runtime-compose:${Versions.LifecycleRuntimeCompose}"
    const val NavigationCompose =
        "androidx.navigation:navigation-compose:${Versions.NavigationCompose}"
    const val HiltNavigationCompose =
        "androidx.hilt:hilt-navigation-compose:${Versions.HiltNavigationCompose}"
    const val HiltAndroid = "com.google.dagger:hilt-android:${Versions.HiltAndroid}"
    const val HiltCompiler = "com.google.dagger:hilt-compiler:${Versions.HiltAndroid}"
    const val KotlinxCoroutinesAndroid =
        "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.KotlinxCoroutinesAndroid}"
    const val KotlinxCoroutinesCore =
        "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.KotlinxCoroutinesAndroid}"
    const val CoilCompose = "io.coil-kt:coil-compose:${Versions.CoilCompose}"
    const val PagingCompose = "androidx.paging:paging-compose:${Versions.PagingCompose}"
    const val PagingCommonKtx = "androidx.paging:paging-common-ktx:${Versions.PagingCompose}"
    const val EspressoCore = "androidx.test.espresso:espresso-core:${Versions.EspressoCore}"
    const val Junit = "junit:junit:${Versions.Junit}"
    const val ExtJunit = "androidx.test.ext:junit:${Versions.ExtJunit}"
    const val CoreTesting = "androidx.arch.core:core-testing:${Versions.CoreTesting}"
    const val Robolectric = "org.robolectric:robolectric:${Versions.Robolectric}"
    const val TestCore = "androidx.test:core:${Versions.TestCore}"
    const val KotlinxCoroutinesTest =
        "org.jetbrains.kotlinx:kotlinx-coroutines-test:${Versions.KotlinxCoroutinesTest}"
    const val MockitoKotlin = "org.mockito.kotlin:mockito-kotlin:${Versions.MockitoKotlin}"
    const val Mockk = "io.mockk:mockk:${Versions.Mockk}"
    const val TestRules = "androidx.test:rules:${Versions.TestRules}"
    const val UiTestJunit4 = "androidx.compose.ui:ui-test-junit4"
    const val UiTestManifest = "androidx.compose.ui:ui-test-manifest"
    const val Turbine = "app.cash.turbine:turbine:${Versions.Turbine}"
    const val Truth = "com.google.truth:truth:${Versions.Truth}"
    const val MockWebserver = "com.squareup.okhttp3:mockwebserver:${Versions.Okhttp3}"
    const val Retrofit2 = "com.squareup.retrofit2:retrofit:${Versions.Retrofit2}"
    const val Retrofit2ConverterGson = "com.squareup.retrofit2:converter-gson:${Versions.Retrofit2}"
    const val Okhttp3 = "com.squareup.okhttp3:okhttp:${Versions.Okhttp3}"
    const val Okhttp3LoggingInterceptor =
        "com.squareup.okhttp3:logging-interceptor:${Versions.Okhttp3}"
    const val KotlinxSerializationJson =
        "org.jetbrains.kotlinx:kotlinx-serialization-json:${Versions.KotlinxSerializationJson}"
    const val RoomRuntime = "androidx.room:room-runtime:${Versions.RoomRuntime}"
    const val RoomCompiler = "androidx.room:room-compiler:${Versions.RoomRuntime}"
    const val RoomKtx = "androidx.room:room-ktx:${Versions.RoomRuntime}"
    const val RoomPaging = "androidx.room:room-paging:${Versions.RoomRuntime}"
}

object Versions {
    const val ActivityCompose = "1.8.2"
    const val ComposeMaterial3 = "1.2.0"
    const val ComposeMaterial = "1.6.0"
    const val ComposeBom = "2023.03.00"
    const val ComposeRuntimeLivedata = "1.6.0"
    const val LifecycleViewModelCompose = "2.7.0"
    const val LifecycleRuntimeCompose = "2.7.0"
    const val NavigationCompose = "2.7.6"
    const val HiltNavigationCompose = "1.1.0"
    const val HiltAndroid = "2.48"
    const val KotlinxCoroutinesAndroid = "1.7.3"
    const val CoilCompose = "2.5.0"
    const val PagingCompose = "3.2.1"
    const val EspressoCore = "3.5.1"
    const val Junit = "4.13.2"
    const val ExtJunit = "1.1.5"
    const val CoreTesting = "2.2.0"
    const val Robolectric = "4.10.3"
    const val TestCore = "1.5.0"
    const val KotlinxCoroutinesTest = "1.7.3"
    const val MockitoKotlin = "3.2.0"
    const val Mockk = "1.13.3"
    const val TestRules = "1.5.0"
    const val Turbine = "1.0.0"
    const val Truth = "1.1.4"
    const val Retrofit2 = "2.9.0"
    const val Okhttp3 = "5.0.0-alpha.12"
    const val KotlinxSerializationJson = "1.6.0"
    const val RoomRuntime = "2.6.1"
}

